### ISSUE TITLE
ChangesetCounter cleanup

### ISSUE THREAD

**Issue by RubenVerborgh** [pabloem/Server.js#1]
The constructor is rather long and has many redundant parts.
- Instead of using local `_year` variables, the components can be directly set on `this._date` (which can at the same time be assigned to a local variable `date` so that `this._date` does not need to be used constantly).
- `input` should not be modified (note that `input = …` is fine, but `input.push` is not)
- in case of an array the type of components is guessed by the first entry; this does not account for mixed objects.

I would propose something like:
- check if undefined, return; else if string, split;
- `date.setYear(parseInt(input.year || input[0], 10) || 0)`, which then catches all cases at once.

In general, avoid underscores for local variables (they are fine for private instance fields).

**Comment by pabloem** [comment]
Commit 74702d8 fixes this issue. The constructor is now a lot shorter. I also added unit tests for it. I'll close now. May reopen if we consider that more work is needed.
