### ISSUE TITLE
Too much is printed through console.log in `LiveHdtDatasource`

### ISSUE THREAD

**Issue by pabloem** [pabloem/Server.js#15]
Gotta clean it up a bit : )

**Comment by RubenVerborgh** [comment]
Perhaps use a logging library (with configurable log output levels)?

**Comment by pabloem** [comment]
I'll add logging with log4js, then. Is that fine?

**Comment by pabloem** [comment]
If you are okay with it, I'll merge b2e1f92 to master. : )

**Comment by RubenVerborgh** [comment]
:+1: perfect

**Comment by pabloem** [comment]
Merged to master. Closing.
