### ISSUE TITLE
Tests in commit hook fail due to timeout

### ISSUE THREAD

**Issue by pabloem** [pabloem/Server.js#6]
We might want to change timeout for mocha in the pre-commit hook to 1000ms?
Just opening for consideration.

**Comment by RubenVerborgh** [comment]
Really? What tests are taking longer?

**Comment by pabloem** [comment]
The HdtDatasource - and also LiveHdtDatasource startup tests are a bit slow. They don't always time out, but sometimes do. It might just be that my computer is slow (it is preeetty slow :) )
What do you think?

**Comment by RubenVerborgh** [comment]
Definitely increase the time then. And get a new computer after GSoC :wink:

**Comment by pabloem** [comment]
Fixed by 6619bf9
