### ISSUE TITLE
Limit calculation is not probabilistic

### ISSUE THREAD

**Issue by pabloem** [pabloem/Server.js#7]
Adding this just to remind myself to do the math and update the code soon. : )

**Comment by pabloem** [comment]
Fixed by 11854da.
We use the Chernoff bound to calculate a limit to ensure we fetch all necessary triples on the first trial with 99.9% probability. We model whether a triple has been removed as a random variable 'ti', that is 0 if a triple with index i has been removed, and 1 otherwise; and we define tN = t0+t1+t2+ ... + tn.

We want to minimize the probability that tN < limit.

We have:

   P[tN < limit] = P[exp(-tN) > exp(-limit)]  <- Here we need to use negative exponents for the Chernoff bound

   P[exp(-tN) > exp(-limit)] < E[exp(-tN)]/exp(-limit)

   If tN < limit, then we must fetch triples again, and thus we have failed. 
   Let P[exp(-tN) > exp(-limit)] = PrFail

   Also, E[exp(-tN)] = E[exp(-t1-t2-...-tn)] = E[-ti]^N = (PrRemoved + PrNotRemoved*exp(-1))^N

   PrFail < E[exp(-ti)]^N/exp(-limit)

   Applying natural logarithm on both sides:
   ln(PrFail) < N*ln(E[exp(-ti)])+limit

   Solving for N: N > (ln(PrFail)-limit) / ln(E[exp(-ti)])

   We choose 99.9% probability of success, and therefore 0.1% probability of failure.
   N > (ln(0.001)-limit) / ln(PrRemoved + PrNotRemoved*exp(-1))

In the code, we also use Math.ceil to fetch the next higher integer.

**Comment by RubenVerborgh** [comment]
Great stuff!
